if( ${CPU_M} STREQUAL "X86" )
	set( IMPL_DIR x86 )
elseif( ${CPU_M} STREQUAL "CORETEXM4" )
	set( IMPL_DIR CORETEXM4 )
elseif( ${CPU_M} STREQUAL "CORETEXM7" )
	set( IMPL_DIR CORETEXM7 )
elseif( ${CPU_M} STREQUAL "ARMv8" )
	set( IMPL_DIR ARMv8 )
endif()